version: "3.8"
services:
  app:
    tty: true
    build:
      context: ../
      dockerfile: ./schuyler/dockerfile
    volumes:
      - ./result:/results
      - ../data:/data
      - /data/huggingface_cache/huggingface/hub/:/models
    command: >
      python3 /experiment/schuyler/experimenter/experiment_script.py --scenario base_experiment --tag comdetaftergreedyModularity
    env_file:
      - ./.env
    depends_on:
      - db
    runtime: nvidia
    environment:
      PYTHONUNBUFFERED: 1
      CUDA_VISIBLE_DEVICES: "0"
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGPASSWORD: password

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
